hopskipnfall/smashbits

.gitignore, server/package.json, server/test/test_helper.js
Sets up package.json under MIT License and pulls in:
Babel with ES6
Chai for unit testing
Immutable.js
Along with some convenience scripts for running tests.
=> Initial project setup for server.

.gitignore, server/package.json, server/src/bits_control.js, server/test/bits_control_test.js
This also sets up more scaffolding for testing.
=> Add trivial ability to add a Bit to state.

client/package.json, client/src/App.js, client/src/Bit.js, client/src/BitsContainer.js, client/src/action_creators.js, client/src/index.js, client/src/reducer.js
Working client-local implementation of up/downvotes on Bits, with Redux integrated.
=> Votes and Redux

client/package.json, client/src/App.js, client/src/BitsContainer.js, client/src/FilterControl.js, client/src/FilterMenu.js, client/src/SortingMenu.js, client/src/action_creators.js, client/src/index.css, client/src/index.js, client/src/reducer.js
Adds tags and filter controls. This only works with the client's Bits right now, but I think we could just use continuations to fetch more if needed once we have those.
=> Filters and tags

client/package.json, client/src/App.js, client/src/Bit.js, client/src/FilterControl.js, client/src/FilterMenu.js, client/src/SortingMenu.js
Migrates us to react-bootstrap, which cuts down on a lot of boilerplate. We'll probably want to move to another component library anyway (something more Material perhaps?), but this is nicer in the meantime anyway.
=> React-bootstrap

client/src/Bit.js, client/src/BitTagPills.js, client/src/BitsContainer.js, client/src/action_creators.js, client/src/index.css, client/src/reducer.js
=> Add tags to bits

client/src/Bit.js, client/src/action_creators.js, client/src/api_client.js, client/src/bits_util.js, client/src/index.js, client/src/reducer.js, server/.babelrc, server/.gitignore, server/index.js, server/package.json, server/serverless.yml, server/src/store.js, server/webpack.config.js
Here's the first working code with the client connecting to a server! We're using AWS Lambda via the Serverless framework. I've moved the hardcoded mock Bits from the client to the server, which is the only thing the server can really do here. There's still a fair bit to clean up, but I'll do that later.
=> Introduce Serverless and wire up to client

client/package.json, client/src/Bit.js, client/src/BitsContainer.js, client/src/CommentsContainer.js, client/src/action_creators.js, client/src/api_client.js, client/src/index.js, client/src/reducer.js, server/index.js, server/serverless.yml, server/src/store.js
Bits and comments are still hardcoded on the server, but the client can fetch comments for a bit and display them in a really basic UI.
=> Added comments fetch and display

server/index.js, server/package.json, server/serverless.yml, server/src/store.js
Stand up a local DynamoDB on local server runs. The serverless function automatically connects to it.
=> Local DynamoDB

server/index.js, server/src/store.js
I included sorting, but not pagination or a URL path to a particular Bit. Here's a sample response, sorted by score: https://gist.github.com/jimmyfnugent/d7fb912119ea765a26b3c433df10aff9
Some maybe useful documentation for Mongoose (NodeJS MongoDB plugin) queries:
https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate-addFields
https://mongoosejs.com/docs/api.html#model_Model.aggregate
https://mongoosejs.com/docs/api.html#query_Query-select
https://docs.mongodb.com/manual/reference/method/cursor.sort/#sort-asc-desc
=> GET implementation for Bits.

client/package.json, client/src/App.js, client/src/Bit.js, client/src/BitPage.js, client/src/CommentsContainer.js, client/src/Home.js, client/src/action_creators.js, client/src/api_client.js, client/src/index.js, client/src/reducer.js, server/index.js, server/src/bits.js, server/src/store.js
This introduces a new page for a standalone Bit. It's not the prettiest page ever, but it's functional:
=> Client implementation for displaying a specific Bit.

client/src/Bit.js, client/src/Home.js, client/src/index.css
=> Switch the thumbs

server/src/bits.js, server/src/store.js
Going with a limit/offset model -- let me know if you have other thoughts.
=> Server impl for pagination.

client/src/CreateBitModal.js, client/src/Home.js, client/src/PageSizeMenu.js, client/src/action_creators.js, client/src/api_client.js, client/src/reducer.js
Basic implementation. Not showing the total number of pages/results, and not really handling the case where we run out of pages in either direction in any real sense.
=> Client impl for pagination

client/package.json, client/src/CreateBitModal.js, client/src/Home.js, client/src/PageSizeMenu.js, client/src/action_creators.js, client/src/api_client.js, client/src/bits_util.js, client/src/fake_api_client.js, client/src/reducer.js, server/src/bits.js, server/src/store.js
I accidentally was always specifying the `limit` and `offset` params, even if they were NaN. Forgot to check that case 😃
=> Fix pagination server params.

.gitignore, client/package-lock.json, package-lock.json, server/package-lock.json, server/package.json
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
=> Add package-lock.json files to repo and add serverless to project.

client/src/LoginButton.jsx, client/src/fake_api_client.ts, server/.eslintrc.json, server/index.js, server/package-lock.json, server/package.json, server/src/User.js, server/src/store.js
This is building towards users not having to log in every time. After this PR, the server should be able to handle looking up a user by session id without needing to OAuth again. Some client work needs to happen to actually request a user profile on load, though.
=> Save users to the DB.

client/.eslintrc.json, client/src/BitPage.jsx, client/src/LoginButton.jsx, client/src/action_creators.js, client/src/api_client.ts
As long as we have the cookie, we can fetch the profile data we need. Here I've chosen to do it whenever we have a LoginButton, since that's the only time we actually need it right now. But we could extend that to profile pages and such in the future.
=> Stay logged in on the client.

client/src/action_creators.ts, client/src/api_client.ts, client/src/reducer.ts
#61 
Note: anywhere that says "any" is an implicit TODO to replace with a real type.
=> Typescriptify some more files

.travis.yml, server/.eslintrc.json, server/package.json, server/src/User.js, server/src/bits.js, server/src/db/bits/bits.methods.ts, server/src/db/bits/bits.schema.ts, server/src/db/bits/bits.statics.ts, server/src/db/db.ts, server/src/store.js
- Fix low-hanging fruit
- Disable some warnings where we haven't cleaned up yet
- Unused variable from error to warning
- Disable tests, disable eslint checks on the client as they don't work yet.
=> Make our CI not unusable
